#!/bin/bash

echo "🔍 Debug Balance Issue - Portfolio vs Send Component"
echo "=================================================="
echo ""
echo "This script helps debug why Send page shows 'No balance available'"
echo "while Portfolio page shows correct balance."
echo ""
echo "Steps:"
echo "1. Make sure the app is running (npm run tauri dev)"
echo "2. Open Portfolio page and check it shows balance"
echo "3. Navigate to Send page and check the console logs"
echo "4. Compare the debug output between Portfolio and Send components"
echo ""
echo "Look for these log messages in the console:"
echo "  - '🔍 Portfolio component balance debug:'"
echo "  - '🔍 Send component balance debug:'"
echo ""
echo "Expected CAIP: bip122:000000000019d6689c085ae165831e93/slip44:0"
echo ""
echo "Things to check:"
echo "  1. Are both components getting portfolio data?"
echo "  2. Do all BTC assets have the expected CAIP?"
echo "  3. Are balances being parsed correctly?"
echo "  4. Is there a timing issue with portfolio loading?"
echo ""
echo "If Send component shows 0 btcAssets but Portfolio shows correct data,"
echo "then there's likely a timing issue or CAIP mismatch."
echo "" 