import { Box, Card, HStack, Text, VStack, Icon } from "@chakra-ui/react";
import { FaBook, FaExclamationTriangle, FaCheckCircle } from "react-icons/fa";

// Step components no longer need props - navigation handled by main wizard

export function Step3Mnemonics() {
  return (
    <Box width="full" maxWidth="2xl">
      <Card.Root bg="gray.900" borderColor="gray.700">
        <Card.Header bg="gray.850">
          <HStack justify="center" gap={3}>
            <Icon asChild color="green.500">
              <FaBook />
            </Icon>
            <Text fontSize="xl" fontWeight="bold" color="white">
              Recovery Phrases
            </Text>
          </HStack>
        </Card.Header>
        <Card.Body>
          <VStack gap={4}>
            <Text color="gray.400" textAlign="center">
              Understanding recovery phrases and backup best practices.
            </Text>
            
            <HStack gap={4} alignItems="stretch" width="full">
              <Box flex="1" p={3} bg="red.900" borderRadius="md" borderColor="red.700" borderWidth="2px">
                <HStack gap={3} mb={3}>
                  <Icon asChild color="red.400">
                    <FaExclamationTriangle />
                  </Icon>
                  <Text color="white" fontWeight="medium">Security Warning</Text>
                </HStack>
                <Text color="red.200" fontSize="sm" mb={2}>
                  Never share your recovery phrase with anyone. KeepKey staff will never ask for it.
                </Text>
                <Text color="red.300" fontSize="sm" fontWeight="bold">
                  Anyone with your recovery phrase can steal your funds!
                </Text>
              </Box>
              
              <Box flex="1" p={3} bg="gray.800" borderRadius="md" borderWidth="2px" borderColor="green.600">
                <HStack gap={3} mb={3}>
                  <Icon asChild color="green.400">
                    <FaCheckCircle />
                  </Icon>
                  <Text color="white" fontWeight="medium">What is a Recovery Phrase?</Text>
                </HStack>
                <VStack align="start" gap={2}>
                  <Text color="gray.400" fontSize="sm">
                    • A 12, 18, or 24-word backup of your entire wallet
                  </Text>
                  <Text color="gray.400" fontSize="sm">
                    • The only way to recover funds if device is lost
                  </Text>
                  <Text color="gray.400" fontSize="sm">
                    • Must be written down and stored securely
                  </Text>
                  <Text color="gray.400" fontSize="sm">
                    • Generated by your KeepKey during setup
                  </Text>
                </VStack>
              </Box>
            </HStack>
            
            <Box textAlign="center" p={3} bg="yellow.900" borderRadius="md" borderWidth="1px" borderColor="yellow.600">
              <Text color="yellow.400" fontSize="sm" fontWeight="medium">
                📝 Have pen and paper ready when you initialize your KeepKey device
              </Text>
            </Box>
          </VStack>
        </Card.Body>
      </Card.Root>
    </Box>
  );
} 